---
- name: load module overlay and br_netfilter
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: setup sysctl params
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present

  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

- name: use systemd as default cgroup for containerd
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '[ ]*SystemdCgroup ='
    line: '            SystemdCgroup = true'
    backrefs: yes

- name: Restart containerd
  service:
    name: containerd
    state: restarted